# Generated by Django 4.1.3 on 2023-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
